//! V8 ELF introspection — read `v8dbg_*` symbols to discover heap object layouts.
//!
//! V8 embeds ~100 `v8dbg_*` data symbols in the Node.js binary that encode
//! internal heap object field offsets, instance type tags, and frame pointer
//! slot positions. These symbols are generated by V8's
//! `gen-postmortem-metadata.py` and are stable enough across versions (with
//! fallbacks) to support introspective profiling.
//!
//! This module reads those symbols from the ELF binary, computes the
//! [`V8IntrospectionData`] struct, and provides [`V8ProcInfo`] for the eBPF
//! V8 unwinder.

use std::collections::HashMap;
use std::path::Path;

use object::read::elf::ElfFile64;
use object::{Endianness, Object, ObjectSection, ObjectSymbol};

use super::types::V8IntrospectionData;

/// Regex-free detection: check if a binary name looks like Node.js.
pub fn is_nodejs_binary(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    // Match: node, node18, nodejs, nsolid, libnode.so, libnode.so.12
    name == "node"
        || name == "nodejs"
        || name == "nsolid"
        || name.starts_with("node") && name[4..].bytes().all(|b| b.is_ascii_digit())
        || name.starts_with("libnode.so")
}

/// Read V8 version from the ELF binary.
///
/// V8 stores its version in three data symbols:
/// - `_ZN2v88internal7Version6major_E` (u32)
/// - `_ZN2v88internal7Version6minor_E` (u32)
/// - `_ZN2v88internal7Version6build_E` (u32)
pub fn read_v8_version(elf_data: &[u8]) -> Option<(u32, u32, u32)> {
    let elf = ElfFile64::<Endianness>::parse(elf_data).ok()?;
    let symbols = build_symbol_map(&elf);

    let major = read_u32_at_symbol(&elf, &symbols, "_ZN2v88internal7Version6major_E")?;
    let minor = read_u32_at_symbol(&elf, &symbols, "_ZN2v88internal7Version6minor_E")?;
    let build = read_u32_at_symbol(&elf, &symbols, "_ZN2v88internal7Version6build_E")?;

    Some((major, minor, build))
}

/// Read all V8 introspection data from a Node.js ELF binary.
///
/// Parses `v8dbg_*` data symbols to discover heap object layouts, instance
/// types, and frame pointer slot positions. Returns `None` if the binary
/// doesn't contain V8 introspection symbols (not a V8 build).
pub fn read_introspection_data(elf_data: &[u8]) -> Option<V8IntrospectionData> {
    let elf = ElfFile64::<Endianness>::parse(elf_data).ok()?;
    let symbols = build_symbol_map(&elf);

    let version = read_v8_version(elf_data)?;
    if version.0 < 8 || (version.0 == 8 && version.1 < 1) {
        tracing::warn!(
            "V8 version {}.{}.{} too old (minimum 8.1.0)",
            version.0,
            version.1,
            version.2
        );
        return None;
    }

    let mut data = V8IntrospectionData {
        version,
        ..Default::default()
    };

    // ── Fixed constants ────────────────────────────────────────────
    data.heap_object_tag_mask =
        read_u32_sym(&elf, &symbols, "v8dbg_HeapObjectTagMask").unwrap_or(3) as u64;
    data.smi_tag_mask = read_u32_sym(&elf, &symbols, "v8dbg_SmiTagMask").unwrap_or(1) as u64;
    data.heap_object_tag = read_u32_sym(&elf, &symbols, "v8dbg_HeapObjectTag").unwrap_or(1) as u16;
    data.smi_tag = read_u32_sym(&elf, &symbols, "v8dbg_SmiTag").unwrap_or(0) as u16;
    data.smi_shift_size = read_u32_sym(&elf, &symbols, "v8dbg_SmiShiftSize").unwrap_or(0) as u16;
    data.first_nonstring_type =
        read_u32_sym(&elf, &symbols, "v8dbg_FirstNonstringType").unwrap_or(0) as u16;
    data.string_encoding_mask =
        read_u32_sym(&elf, &symbols, "v8dbg_StringEncodingMask").unwrap_or(0) as u16;
    data.string_representation_mask =
        read_u32_sym(&elf, &symbols, "v8dbg_StringRepresentationMask").unwrap_or(0) as u16;
    data.seq_string_tag = read_u32_sym(&elf, &symbols, "v8dbg_SeqStringTag").unwrap_or(0) as u16;
    data.cons_string_tag = read_u32_sym(&elf, &symbols, "v8dbg_ConsStringTag").unwrap_or(0) as u16;
    data.one_byte_string_tag =
        read_u32_sym(&elf, &symbols, "v8dbg_OneByteStringTag").unwrap_or(0) as u16;
    data.two_byte_string_tag =
        read_u32_sym(&elf, &symbols, "v8dbg_TwoByteStringTag").unwrap_or(0) as u16;
    data.thin_string_tag = read_u32_sym(&elf, &symbols, "v8dbg_ThinStringTag").unwrap_or(0) as u16;
    data.sliced_string_tag =
        read_u32_sym(&elf, &symbols, "v8dbg_SlicedStringTag").unwrap_or(0) as u16;

    // ── FP context offsets (signed byte offsets relative to FP) ────
    data.fp_function = read_u32_sym(&elf, &symbols, "v8dbg_off_fp_function")
        .map(|v| v as i8)
        .unwrap_or(0);
    data.fp_context = read_u32_sym(&elf, &symbols, "v8dbg_off_fp_context")
        .map(|v| v as i8)
        .unwrap_or(0);
    data.fp_bytecode_offset = read_u32_sym(&elf, &symbols, "v8dbg_off_fp_bytecode_offset")
        .map(|v| v as i8)
        .unwrap_or(0);
    data.fp_bytecode_array = read_u32_sym(&elf, &symbols, "v8dbg_off_fp_bytecode_array")
        .map(|v| v as i8)
        .unwrap_or(0);

    // Fallbacks for missing FP offsets (from OTel: v8.go:1930-1945)
    if data.fp_bytecode_array == 0 && data.fp_function != 0 {
        if version >= (8, 7, 198) {
            data.fp_bytecode_array = data.fp_function.wrapping_sub(16); // Function - 2*8
        } else {
            data.fp_bytecode_array = data.fp_function.wrapping_sub(8);
        }
    }
    if data.fp_bytecode_offset == 0 && data.fp_bytecode_array != 0 {
        data.fp_bytecode_offset = data.fp_bytecode_array.wrapping_sub(8);
    }

    // ── HeapObject ─────────────────────────────────────────────────
    data.off_heap_object_map =
        read_u32_sym(&elf, &symbols, "v8dbg_class_HeapObject__map__Map").unwrap_or(0);

    // ── Map ────────────────────────────────────────────────────────
    data.off_map_instance_type =
        read_u32_sym(&elf, &symbols, "v8dbg_class_Map__instance_type__uint16_t").unwrap_or(0);

    // ── JSFunction ─────────────────────────────────────────────────
    data.off_jsfunction_shared = read_u32_sym(
        &elf,
        &symbols,
        "v8dbg_class_JSFunction__shared__SharedFunctionInfo",
    )
    .unwrap_or(0);
    data.off_jsfunction_code = read_u32_sym(&elf, &symbols, "v8dbg_class_JSFunction__code__Code")
        .or_else(|| read_u32_sym(&elf, &symbols, "v8dbg_class_JSFunction__code__Tagged_Code_"))
        .unwrap_or(0);

    // Fallback for JSFunction.code (OTel: v8.go:1974-1981)
    if data.off_jsfunction_code == 0 && data.off_jsfunction_shared != 0 {
        if version >= (11, 7, 368) {
            data.off_jsfunction_code = data.off_jsfunction_shared.wrapping_sub(8);
        } else {
            data.off_jsfunction_code = data.off_jsfunction_shared.wrapping_add(24);
        }
    }

    // ── Code ───────────────────────────────────────────────────────
    data.off_code_instruction_start = read_u32_sym(
        &elf,
        &symbols,
        "v8dbg_class_Code__instruction_start__uintptr_t",
    )
    .or_else(|| {
        read_u32_sym(
            &elf,
            &symbols,
            "v8dbg_class_Code__instruction_start__Address",
        )
    })
    .unwrap_or(0);
    data.off_code_instruction_size =
        read_u32_sym(&elf, &symbols, "v8dbg_class_Code__instruction_size__int").unwrap_or(0);
    data.off_code_flags =
        read_u32_sym(&elf, &symbols, "v8dbg_class_Code__flags__uint32_t").unwrap_or(0);
    data.off_code_deoptimization_data = read_u32_sym(
        &elf,
        &symbols,
        "v8dbg_class_Code__deoptimization_data__FixedArray",
    )
    .or_else(|| {
        read_u32_sym(
            &elf,
            &symbols,
            "v8dbg_class_Code__deoptimization_data__Tagged_FixedArray_",
        )
    })
    .unwrap_or(0);
    data.off_code_source_position_table = read_u32_sym(
        &elf,
        &symbols,
        "v8dbg_class_Code__source_position_table__ByteArray",
    )
    .or_else(|| {
        read_u32_sym(
            &elf,
            &symbols,
            "v8dbg_class_Code__source_position_table__Tagged_ByteArray_",
        )
    })
    .unwrap_or(0);

    // Code field fallbacks (OTel: v8.go:1983-2038)
    if data.off_code_flags == 0 && data.off_code_instruction_size != 0 {
        data.off_code_flags = data.off_code_instruction_size.wrapping_add(8);
    }
    if data.off_code_deoptimization_data == 0 && data.off_code_source_position_table != 0 {
        data.off_code_deoptimization_data = data.off_code_source_position_table.wrapping_sub(8);
    }

    // code_instructions_is_pointer: V8 >= 11.1.204 changed instruction_start
    // from inline bytes to a pointer
    data.code_instructions_is_pointer = version >= (11, 1, 204);

    // ── SharedFunctionInfo ─────────────────────────────────────────
    data.off_sfi_name_or_scope_info = first_of(
        &elf,
        &symbols,
        &[
            "v8dbg_class_SharedFunctionInfo__name_or_scope_info__Object",
            "v8dbg_class_SharedFunctionInfo__name_or_scope_info__Tagged_Object_",
            "v8dbg_class_SharedFunctionInfo__name_or_scope_info__Tagged_NameOrScopeInfoT_",
        ],
    )
    .unwrap_or(0);
    data.off_sfi_function_data = first_of(
        &elf,
        &symbols,
        &[
            "v8dbg_class_SharedFunctionInfo__function_data__Object",
            "v8dbg_class_SharedFunctionInfo__function_data__Tagged_Object_",
        ],
    )
    .unwrap_or(8); // OTel fallback: hardcoded 8
    data.off_sfi_script_or_debug_info = first_of(
        &elf,
        &symbols,
        &[
            "v8dbg_class_SharedFunctionInfo__script_or_debug_info__Object",
            "v8dbg_class_SharedFunctionInfo__script_or_debug_info__HeapObject",
            "v8dbg_class_SharedFunctionInfo__script__Tagged_HeapObject_",
        ],
    )
    .unwrap_or(0);

    // ── Script ─────────────────────────────────────────────────────
    data.off_script_name =
        read_u32_sym(&elf, &symbols, "v8dbg_class_Script__name__Object").unwrap_or(0);
    data.off_script_line_ends =
        read_u32_sym(&elf, &symbols, "v8dbg_class_Script__line_ends__Object").unwrap_or(0);
    data.off_script_source = read_u32_sym(&elf, &symbols, "v8dbg_class_Script__source__Object")
        .unwrap_or_else(|| {
            // Fallback: source is 8 bytes before name
            data.off_script_name.saturating_sub(8)
        });

    // ── String ─────────────────────────────────────────────────────
    data.off_string_length =
        read_u32_sym(&elf, &symbols, "v8dbg_class_String__length__int32_t").unwrap_or(0);
    data.off_seq_one_byte_string_chars =
        read_u32_sym(&elf, &symbols, "v8dbg_class_SeqOneByteString__chars__char").unwrap_or(0);
    data.off_cons_string_first =
        read_u32_sym(&elf, &symbols, "v8dbg_class_ConsString__first__String").unwrap_or(0);
    data.off_cons_string_second =
        read_u32_sym(&elf, &symbols, "v8dbg_class_ConsString__second__String").unwrap_or(0);
    data.off_thin_string_actual =
        read_u32_sym(&elf, &symbols, "v8dbg_class_ThinString__actual__String").unwrap_or(0);

    // ── FixedArray ─────────────────────────────────────────────────
    data.off_fixed_array_base_length =
        read_u32_sym(&elf, &symbols, "v8dbg_class_FixedArrayBase__length__SMI").unwrap_or(0);
    data.off_fixed_array_data =
        read_u32_sym(&elf, &symbols, "v8dbg_class_FixedArray__data__uintptr_t").unwrap_or(0);

    // ── BytecodeArray ──────────────────────────────────────────────
    data.off_bytecode_array_source_position_table = first_of(
        &elf,
        &symbols,
        &[
            "v8dbg_class_BytecodeArray__source_position_table__Object",
            "v8dbg_class_BytecodeArray__source_position_table__Tagged_HeapObject_",
        ],
    )
    .unwrap_or(0);

    // ── Instance types ─────────────────────────────────────────────
    data.type_jsfunction =
        read_u32_sym(&elf, &symbols, "v8dbg_type_JSFunction__JS_FUNCTION_TYPE").unwrap_or(0) as u16;
    data.type_code = read_u32_sym(&elf, &symbols, "v8dbg_type_Code__CODE_TYPE").unwrap_or(0) as u16;
    data.type_shared_function_info = read_u32_sym(
        &elf,
        &symbols,
        "v8dbg_type_SharedFunctionInfo__SHARED_FUNCTION_INFO_TYPE",
    )
    .unwrap_or(0) as u16;
    data.type_scope_info =
        read_u32_sym(&elf, &symbols, "v8dbg_type_ScopeInfo__SCOPE_INFO_TYPE").unwrap_or(0) as u16;
    data.type_script =
        read_u32_sym(&elf, &symbols, "v8dbg_type_Script__SCRIPT_TYPE").unwrap_or(0) as u16;
    data.type_bytecode_array = read_u32_sym(
        &elf,
        &symbols,
        "v8dbg_type_BytecodeArray__BYTECODE_ARRAY_TYPE",
    )
    .unwrap_or(0) as u16;
    data.type_fixed_array =
        read_u32_sym(&elf, &symbols, "v8dbg_type_FixedArray__FIXED_ARRAY_TYPE").unwrap_or(0) as u16;
    data.type_byte_array =
        read_u32_sym(&elf, &symbols, "v8dbg_type_ByteArray__BYTE_ARRAY_TYPE").unwrap_or(0) as u16;

    // ── JSFunction type range ──────────────────────────────────────
    data.first_jsfunction_type =
        read_u32_sym(&elf, &symbols, "v8dbg_FirstJSFunctionType").unwrap_or(0) as u16;
    data.last_jsfunction_type =
        read_u32_sym(&elf, &symbols, "v8dbg_LastJSFunctionType").unwrap_or(0) as u16;

    // Fallback: compute JSFunction type range from single type (OTel: v8.go:1948-1972)
    if data.first_jsfunction_type == 0 && data.type_jsfunction != 0 {
        data.first_jsfunction_type = data.type_jsfunction;
        let range = if version >= (9, 6, 138) {
            15
        } else if version >= (9, 0, 14) {
            14
        } else {
            1
        };
        data.last_jsfunction_type = data.first_jsfunction_type + range - 1;
    }

    // ── CodeKind ───────────────────────────────────────────────────
    data.codekind_field_mask = read_u32_sym(&elf, &symbols, "v8dbg_CodeKindFieldMask").unwrap_or(0);
    data.codekind_field_shift =
        read_u32_sym(&elf, &symbols, "v8dbg_CodeKindFieldShift").unwrap_or(0) as u8;
    data.codekind_baseline =
        read_u32_sym(&elf, &symbols, "v8dbg_CodeKindBaseline").unwrap_or(0xff) as u8;

    // CodeKind fallback (OTel: v8.go:2065-2071)
    if data.codekind_baseline == 0xff && version >= (9, 0, 240) {
        data.codekind_field_mask = 0xf;
        data.codekind_field_shift = 0;
        data.codekind_baseline = 11;
    }

    // Validate essential fields
    if data.off_map_instance_type == 0
        || data.type_jsfunction == 0
        || data.type_shared_function_info == 0
        || data.off_jsfunction_shared == 0
        || data.first_jsfunction_type == 0
        || data.last_jsfunction_type < data.first_jsfunction_type
    {
        tracing::warn!(
            "V8 {}.{}.{}: essential v8dbg_* symbols missing or invalid \
             (map_instance_type={}, jsfunction={}, sfi={}, jsfunction_shared={}, \
             type_range=[{}, {}])",
            version.0,
            version.1,
            version.2,
            data.off_map_instance_type,
            data.type_jsfunction,
            data.type_shared_function_info,
            data.off_jsfunction_shared,
            data.first_jsfunction_type,
            data.last_jsfunction_type,
        );
        return None;
    }

    tracing::info!(
        "V8 {}.{}.{} introspection loaded: JSFunction type range [{}, {}], Map.instance_type offset {}",
        version.0, version.1, version.2,
        data.first_jsfunction_type, data.last_jsfunction_type,
        data.off_map_instance_type,
    );

    Some(data)
}

// ── ELF helper functions ───────────────────────────────────────────────────

/// Build a symbol name → virtual address map from the ELF symbol table.
fn build_symbol_map(elf: &ElfFile64<Endianness>) -> HashMap<String, u64> {
    let mut map = HashMap::new();
    for sym in elf.symbols() {
        if let Ok(name) = sym.name() {
            if name.starts_with("v8dbg_") || name.starts_with("_ZN2v8") {
                map.insert(name.to_string(), sym.address());
            }
        }
    }
    // Also check dynamic symbols
    for sym in elf.dynamic_symbols() {
        if let Ok(name) = sym.name() {
            if name.starts_with("v8dbg_") || name.starts_with("_ZN2v8") {
                map.entry(name.to_string()).or_insert(sym.address());
            }
        }
    }
    map
}

/// Read a u32 value stored at the virtual address of a named ELF symbol.
///
/// V8's `v8dbg_*` symbols are data symbols — their `st_value` is an address
/// in `.data`/`.rodata` pointing to a 4-byte integer. We resolve the address
/// to a file offset via the section headers and read the value.
fn read_u32_at_symbol(
    elf: &ElfFile64<Endianness>,
    symbols: &HashMap<String, u64>,
    name: &str,
) -> Option<u32> {
    let &vaddr = symbols.get(name)?;
    read_u32_at_vaddr(elf, vaddr)
}

/// Shorthand for read_u32_at_symbol with the common pattern.
fn read_u32_sym(
    elf: &ElfFile64<Endianness>,
    symbols: &HashMap<String, u64>,
    name: &str,
) -> Option<u32> {
    read_u32_at_symbol(elf, symbols, name)
}

/// Try multiple symbol names, return the first one that resolves.
fn first_of(
    elf: &ElfFile64<Endianness>,
    symbols: &HashMap<String, u64>,
    names: &[&str],
) -> Option<u32> {
    names
        .iter()
        .find_map(|name| read_u32_at_symbol(elf, symbols, name))
}

/// Read a little-endian u32 at a virtual address by finding which section
/// contains it and computing the file offset.
/// Uses checked arithmetic to safely handle malformed ELF metadata.
fn read_u32_at_vaddr(elf: &ElfFile64<Endianness>, vaddr: u64) -> Option<u32> {
    // Hoist the loop-invariant vaddr end check — if this overflows,
    // the address is invalid regardless of section.
    let vaddr_end = vaddr.checked_add(4)?;

    for section in elf.sections() {
        let sec_addr = section.address();
        let sec_size = section.size();
        // Per-section overflow: skip this section, don't abort the search.
        let Some(sec_end) = sec_addr.checked_add(sec_size) else {
            continue;
        };
        if vaddr >= sec_addr && vaddr_end <= sec_end {
            let Some(offset) = vaddr.checked_sub(sec_addr).map(|o| o as usize) else {
                continue;
            };
            let Ok(data) = section.data() else {
                continue;
            };
            let Some(end) = offset.checked_add(4) else {
                continue;
            };
            if end <= data.len() {
                return Some(u32::from_le_bytes([
                    data[offset],
                    data[offset + 1],
                    data[offset + 2],
                    data[offset + 3],
                ]));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_nodejs_binary() {
        assert!(is_nodejs_binary(Path::new("/usr/bin/node")));
        assert!(is_nodejs_binary(Path::new("/usr/bin/nodejs")));
        assert!(is_nodejs_binary(Path::new("/usr/bin/nsolid")));
        assert!(is_nodejs_binary(Path::new("node")));
        assert!(is_nodejs_binary(Path::new("/usr/bin/node18")));
        assert!(is_nodejs_binary(Path::new("/usr/lib/libnode.so")));
        assert!(is_nodejs_binary(Path::new("/usr/lib/libnode.so.12")));
        assert!(!is_nodejs_binary(Path::new("/usr/bin/python3")));
        assert!(!is_nodejs_binary(Path::new("/usr/bin/nodemon")));
    }
}
