/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pt_regs {
    pub r15: ::aya_ebpf::cty::c_ulong,
    pub r14: ::aya_ebpf::cty::c_ulong,
    pub r13: ::aya_ebpf::cty::c_ulong,
    pub r12: ::aya_ebpf::cty::c_ulong,
    pub bp: ::aya_ebpf::cty::c_ulong,
    pub bx: ::aya_ebpf::cty::c_ulong,
    pub r11: ::aya_ebpf::cty::c_ulong,
    pub r10: ::aya_ebpf::cty::c_ulong,
    pub r9: ::aya_ebpf::cty::c_ulong,
    pub r8: ::aya_ebpf::cty::c_ulong,
    pub ax: ::aya_ebpf::cty::c_ulong,
    pub cx: ::aya_ebpf::cty::c_ulong,
    pub dx: ::aya_ebpf::cty::c_ulong,
    pub si: ::aya_ebpf::cty::c_ulong,
    pub di: ::aya_ebpf::cty::c_ulong,
    pub orig_ax: ::aya_ebpf::cty::c_ulong,
    pub ip: ::aya_ebpf::cty::c_ulong,
    pub cs: ::aya_ebpf::cty::c_ulong,
    pub flags: ::aya_ebpf::cty::c_ulong,
    pub sp: ::aya_ebpf::cty::c_ulong,
    pub ss: ::aya_ebpf::cty::c_ulong,
}
